// import './example/basic-type'
// import './example/symbol'
// import './example/interface';
// import './example/function'
// import './example/generics'
// import './example/ES6class1'
// import './example/ES6class2'
// import './example/class'
// import './example/enum'
// import './example/inference-compatibility'
// import './example/advancedType1'
import './example/advancedType2'